# Generated by Django 3.2.3 on 2021-08-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_avtive',
            new_name='is_active',
        ),
    ]
